# Generated by Django 3.0.8 on 2020-07-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200723_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='already_read',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
