# Generated by Django 3.0.8 on 2020-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_already'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='already',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
