# Generated by Django 3.0.8 on 2020-07-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200727_2147'),
        ('accounts', '0004_auto_20200729_1729'),
    ]

    operations = [
    ]
