# Generated by Django 3.0.8 on 2020-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200731_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='already_read',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
