# Generated by Django 3.0.8 on 2020-08-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20200731_1648'),
        ('accounts', '0009_auto_20200731_1748'),
    ]

    operations = [
    ]
