# Generated by Django 3.0.8 on 2020-07-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
