# Generated by Django 3.0.8 on 2020-08-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
