# Generated by Django 3.0.8 on 2020-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20200727_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
