# Generated by Django 3.0.8 on 2020-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_auto_20200727_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
